# 02.01 numpy.array
----

## 函數與方法

- 建立

```arange``` ```array``` ```copy``` ```empty``` ```empty_like``` ```eye``` ```fromfile``` ```fromfunction``` ```identity``` ```linspace``` ```logspace``` ```mgrid``` ```ogrid``` ```ones``` ```ones_like``` ```zeros``` ```zeros_like```

- 轉換

```ndarray.astype``` ```atleast_1d``` ```atleast_2d``` ```atleast_3d``` ```mat```

- 操作

```array_split``` ```column_stack``` ```concatenate``` ```diagonal``` ```dsplit``` ```dstack``` ```hsplit``` ```hstack``` ```ndarray.item``` ```newaxis``` ```ravel``` ```repeat``` ```reshape``` ```resize``` ```squeeze``` ```swapaxes``` ```take``` ```transpose``` ```vsplit``` ```vstack```

- 檢查

```all``` ```any``` ```nonzero``` ```where```

- 尋找

```argmax``` ```argmin``` ```argsort``` ```max``` ```min``` ```ptp``` ```searchsorted``` ```sort```

- 計算

```choose``` ```compress``` ```cumprod``` ```cumsum``` ```inner``` ```ndarray.fill``` ```imag``` ```prod``` ```put``` ```putmask``` ```real``` ```sum```

- 統計

```cov``` ```mean``` ```std``` ```var```

- 線性代數

```cross``` ```dot``` ```outer``` ```linalg.svd``` ```vdot```

----

## ufunc

ufunc 是 universal function 的縮寫，他是對 narry 的每個元素進行運算的函數。 (P.56)

當 ufunc 函數對兩個不同形狀的 narray 進行計算時，會進行 **廣播 (broadcasting)** 處理。 (P.62)

np.ogrid[start : end : step, s : e : t] 回傳一組可以用來廣播的 narray，np.mgrid[s : e : t,s : e : t] 是其廣播後的樣子。其中 start : end : step 與 np.arange 類似，如果想要跟 np.linspace 類似，則 step 要以 **整數+j** 表示。 (P.65)

----

## multi-index

narray 的 index 應為一個長度與 narray 維度相同的 tuple，若 tuple 的長度比 narray 的維度大，則出錯，若較小，則會在 index 缺少的維度使用 **:** 代替，如果 index 不是 tuple，則 NumPy 會先試圖將他轉換為 tuple。

如下 lidx 被轉換成 ([0], [1])，而 narray 的 aidx 被視為 (aidx,:,:)。 (P.69)

In [1]:
import numpy as np

a = np.arange(3 * 4 * 5).reshape(3, 4, 5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [2]:
import numpy as np

lidx = [[0], [1]]
aidx = np.array(lidx)

print("a[0,1] =\n",  a[0,1], "\n")
print("a[lidx] =\n", a[lidx], "\n")
print("a[[0], [1], :] =\n", a[[0], [1], :], "\n")
print("a[aidx] =\n", a[aidx], "\n")
print("a[[[0], [1]], :, :] =\n", a[[[0], [1]], :, :])

a[0,1] =
 [5 6 7 8 9] 

a[lidx] =
 [[5 6 7 8 9]] 

a[[0], [1], :] =
 [[5 6 7 8 9]] 

a[aidx] =
 [[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]]]] 

a[[[0], [1]], :, :] =
 [[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]]]]


此例也可以注意到 3d narry 的 index tuple 概念依序是 [**height**, **row**, **column**]。